### ISSUE TITLE
Configurable available and autostart modules

### ISSUE THREAD

**Issue by wolferCZ** [ActivityWatch/aw-qt#47] opened 2019-11-06 13:15 UTC
As a developer I would like to integrate my private watchers to the `aw-qt` without necessity to alter the `aw-qt` and maintain my own fork.

Currently `aw-qt` (v0.8.0b9) supports only few modules that are hard-coded in:
https://github.com/ActivityWatch/aw-qt/blob/fcb59268c43d7a0f61658d78c1f6ace8ef38d012/aw_qt/manager.py#L129

***

**Posible solutions:**

Based on TODO in https://github.com/ActivityWatch/aw-qt/blob/fcb59268c43d7a0f61658d78c1f6ace8ef38d012/aw_qt/manager.py#L127

> `aw_qt/manager.py`:
> ```python
> # TODO: Fetch these from somewhere appropriate (auto detect or a config file)
> #       Save to config wether they should autostart or not.
> _possible_modules = [
>     "aw-server",
>     "aw-watcher-afk",
>     "aw-watcher-window",
>     # "aw-watcher-spotify",
>     # "aw-watcher-network"
> ]
> ```

1. Available modules and modules to be started automatically will be listed in new `aw-qt` configuration.
2. Autodetect available modules. Modules to be started automatically will be listed in new `aw-qt` configuration.

NOTE: Available modules can be separated to independent issue/story (nice to have).

**Comment by ErikBjare** [comment] 2019-11-06 13:19
Seems like a duplicate of #35?

**Comment by wolferCZ** [comment] 2019-11-06 13:22
> Seems like a duplicate of #35?
:man_facepalming: Yes, my bad.

**Comment by ErikBjare** [comment] 2020-04-19 15:11
Duplicate of #35, worked on in PR #56

**Closed by ErikBjare** 2020-04-19 15:11 UTC
Labels: duplicate
